### ISSUE TITLE
Validate plugins with order less than 1 are being skipped

### ISSUE THREAD

**Issue by RafaelVillar** [pyblish/pyblish-lite#120]
Hello @mottosso and @chadmv 
I think the fix implemented in #114 created an issue where validate plugins are not processed in the UI if their order is less than api.ValidatorOrder(1)

One of the developers on the team noticed that certain validate plugins were not being executed in the UI after we updated to the latest release. After some exhaustive searching, I found that the [_reset_iterator](https://github.com/pyblish/pyblish-lite/pull/114/files#diff-0f96f5b2a10ea922a245627cb0750249c31a9b61939f5323df1fd02399418575R84) was not taking into account that plugins can be within a range of ValidatorOrder, not just start there. 

So if you had a plugin order of
`order = pyblish.api.ValidatorOrder - .05`
It would not get processed when validating in the UI (flask button). :(

So with the latest update, the result would look like so. 
![pyblish_v0001](https://user-images.githubusercontent.com/7085330/105967271-0136e580-60c9-11eb-9f0c-278aa8f8cbcc.gif)

vs the previous install 0.8.7 and/or a fix

![pyblish_v0002](https://user-images.githubusercontent.com/7085330/105967469-36dbce80-60c9-11eb-8f44-ba48af42e237.gif)

I do not know what would be the most efficient fix, but I tested this solution and it worked as in previous versions. 

```
  def validate(self):
      # The iterator doesn't sync with the GUI check states so
      # reset the iterator to ensure we grab the updated instances
      # assuming the plugins are already sorted from api.Discover()
      start_validator_from = pyblish.api.ValidatorOrder
      for plugin in self.plugins:
          if pyblish.lib.inrange(plugin.order, pyblish.api.ValidatorOrder):
              start_validator_from = plugin.order
              break

      self._reset_iterator(start_from=start_validator_from)
      self._run(until=pyblish.api.ValidatorOrder,
                on_finished=self.on_validated)
```
https://github.com/pyblish/pyblish-lite/blob/master/pyblish_lite/control.py#L84

Hopefully, this works for everyone.

**Comment by mottosso** [comment]
Thanks @RafaelVillar, would it be possible to turn this into a PR? That way we can spot the differences and have the automated tests kick in with an extra pair of eyes.

**Comment by hannesdelbeke** [comment]
can we close this issue? PR has been merged
