### ISSUE TITLE
Add Validate button

### ISSUE THREAD

**Issue by larsbijl** [pyblish/pyblish-lite#22]
### goal
similarly to QML having a valdiate button to verify the publish will work.

**Comment by mottosso** [comment]
Also allow publishing to *continue* after validating.

**Comment by mottosso** [comment]
### Implementation

For this to work, we effectively have to enable "pausing" of the current state of processing.

Conceptually, there are four phases of processing.

```
 _____________
|             |<-----
| Collection  |
|_____________|
|             |
| Validation  |
|_____________|
|             |
| Extraction  |
|_____________|
|             |
| Integration |
|_____________|
```

We'd like to initiate this "pool" of tasks during startup of the GUI, and then continue running it with the buttons; one continues all the way (play) and the other continues only up till extraction, not including (validate).

Once this is in there, arbitrarily pausing is a function call away as well.

**Comment by mottosso** [comment]
Here is some progress on continuing and pausing. @larsbijl could you take a look and tell me what you think?

This is rather complex stuff but there might be a more straightforward way, so put on your critical goggles.

It involves:

1. Starting a mutable* Python generator
1. A few plug-ins
1. Starting and stopping processing at various points; e.g. Collection, Validation and all.

Once implemented, I'm expecting this to sit at the core of the GUI; each button press would either restart or continue the generator. In this case, validation would continue from where collection left off, and stop at extraction, regardless of problems.

Later, if validation has run but there were problems, an action should be able to resolve a problem, and thus allow processing to continue without the need to re-validate.

Also, arbitrary pausing processing.

```python
def test_iterator_reset():
    # Test data
    count = {"#": 0}

    class MyCollector(pyblish.api.ContextPlugin):
        order = pyblish.api.CollectorOrder

        def process(self, context):
            context.create_instance("myInstance")
            count["#"] += 1
            self.log.info("Collecting..")

    class MyValidator(pyblish.api.InstancePlugin):
        order = pyblish.api.ValidatorOrder

        def process(self, instance):
            print("Validating %s" % instance)
            count["#"] += 10

    class MyExtractor(pyblish.api.InstancePlugin):
        order = pyblish.api.ExtractorOrder

        def process(self, instance):
            count["#"] += 100

    # Data maintained by the GUI
    state = {
        "current": None,
        "context": pyblish.api.Context(),
        "plugins": [MyCollector, MyValidator, MyExtractor]
    }

    def load():
        """Initiate new generator and load first pair"""
        state["generator"] = pyblish.logic.Iterator(state["plugins"],
                                                    state["context"])
        state["current"] = next(state["generator"], None)

    def process(until):
        """Process current pair and store next pair for next process

        Arguments:
            until (pyblish.api.Order): Keep fetching next() until this order

        """

        while state["current"]:
            plugin, instance = state["current"]

            if plugin.order > (until + 0.5):
                break

            pyblish.plugin.process(plugin, state["context"], instance)

            state["current"] = next(state["generator"], None)

    # Happens once, during reset
    load()

    # This should only run up until collection
    process(until=pyblish.api.CollectorOrder)

    assert count["#"] == 1, count

    # This should *continue* processing, until validation
    process(until=pyblish.api.ValidatorOrder)

    assert count["#"] == 11, count

    # Run all remaining plug-ins..
    process(until=pyblish.api.IntegratorOrder)

    assert count["#"] == 111, count
```

**Comment by larsbijl** [comment]
this makes sense.

my only worry would be how can we go back from after validating back to validate and extract.
in essence is it possible to `undo` the validation and run that again?

**Comment by mottosso** [comment]
Wouldn't that be simply resetting?

1. Start -> Validate -> Publish
2. Start -> Validate -> Reset -> Publish (implies validate)

**Comment by larsbijl** [comment]
but without collection and loosing the state of instances.

**Comment by mottosso** [comment]
Sorry, I'm not sure I follow. Resetting implies Collection? After you've validated, you can either continue, which would run extraction, or reset, which clears the iterator and would force a re-run of validation.

**Comment by larsbijl** [comment]
correct but lets say.

you validate and something when't wrong. you would need to force a re-validation and resetting back to collection would break usability.

same thing goes for if it all went right. if they change there scene between validation and extractions is not worth the risk. re-running the validators doesn't take long and adds security

**Comment by mottosso** [comment]
> you would need to force a re-validation and resetting back to collection would break usability.

Break usability how? Isn't this how it is currently, when validation fails? I'm probably not seeing what you're seeing.

> if they change there scene between validation and extractions is not worth the risk. re-running the validators doesn't take long and adds security

Yes, that is a risk, but I've got an idea for this. Basically, if the window looses focus between validating and publishing, the publish option will either vanish or the user can be required to choose whether to continue or restart.

Losing focus is a hard-constraint that is very difficult to bypass even if they tried.

Also, are you going back on https://github.com/pyblish/pyblish-qml/issues/195?

**Comment by larsbijl** [comment]
yes I am. if running validate means resetting completely it to be able to run validate again it makes it harder for TD's to quickly iterate in writing there validators or extractors.

it's happened to me multiple times where I was writing a extractor or validator. broke it. had to reset and forgot to turn off my ftrack integrator. the end up publishing half broken setup.

maybe it's just a developers annoyance.

**Comment by mottosso** [comment]
> if running validate means resetting completely it to be able to run validate again it makes it harder for TD's to quickly iterate in writing there validators or extractors.

For new or altered plug-ins to get picked up, it would have to reset. That's the part that rediscovers plug-ins, and also runs collection to discover instances.

As you say, this is more a developer issue than an end-user issue. I think a workflow alternative might be better suited here.

For example, rather than developing a single plug-in and having all plug-ins registered, write your plug-in in isolation, and trigger the GUI showcasing only relevant plug-ins.

```python
import pyblish.api

class MyWipPlugin(pyblish.api.ContextPlugin):
  ...

pyblish.api.register_plugin(MyWipPlugin)

for plugin in pyblish.api.discover():
  if plugin.__name__ in ("MyCollector", "MyValidator"):
    pyblish.api.register_plugin(plugin)

import pyblish_lite
pyblish_lite.show()
```

That way, you can run the GUI with only the plug-ins you are currently working on and save the "integration" or "blackbox" tests, where you run all at once, for last.

> the end up publishing half broken setup.

This I think would be solved by the validate-only button itself. The main thing about this particular iterator is that we would be able to continue from where validation left off when publishing, or whether it should reset completely as it does in QML.

**Comment by larsbijl** [comment]
fair enough I can live with that.

in that case I like the idea of if the user looses focus it removes the publish button and resets.
might confuse users at first though.
