### ISSUE TITLE
Detail View

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-lite#25]
### Goal

Enable detailed inspection of instances and plug-ins.

**QML reference**

![](http://forums.pyblish.com/uploads/default/original/1X/4833099b21ecad6657e0364671ed5396c4fa2986.gif)

### Implementation

Unlike QML, the detailed view will be accessible via middle-click, like in Houdini.

![](https://lh3.ggpht.com/-29Cv-WMjpds/UfkJkjYJ5AI/AAAAAAAAAbA/8SXDQ3eFOjs/s400/Screen+Shot+2013-07-31+at+13.54.47.png)

Unlike Houdini, the middle-clicked panel can optionally stick around and provide scrollbars in case there is lots of information, such as logs. Sticking around is enabled via a "pin" toggle on the panel itself, where the GUI is deactivated on mouseLeave.

The goal is a quick and effortless inspection of the critical details an item without delay, followed by an optional deeper inspection for full details and options.

**Comment by mkolar** [comment]
This has brought one issue that was discussed somewhere on the forums before I believe. 

Using middle mouse button for inspection, prevents tablet users from using it for scrolling and they have to click on the scrol bar.

Another issue with this approach is, that the details don't stay on the screen after the middle button release, so they can't be copied into the clipboard. Almost everytime a user runs into a trouble and they need to check what happened, they copy the error messages and send them to their TD to have a look at. This currently prevents that behavior. 

As nice as it is (I'm a long time houdini user, so I appreciate the familiarity), I'd say that QML implementation makes more sense and is more usable.

**Comment by mottosso** [comment]
> Using middle mouse button for inspection, prevents tablet users from using it for scrolling and they have to click on the scrol bar.

I'm on a tablet.

How do you mean it prevents scrolling? You can't scroll with middle-click?

> I'd say that QML implementation makes more sense and is more usable.

Do you mean this? https://github.com/pyblish/pyblish-lite/issues/36 The idea is to have both, this being the mode agile alternative.

**Comment by mkolar** [comment]
> Do you mean this? #36 

Ah. yes, totally missed that.

> You can't scroll with middle-click?

Precisely. Normally when using tablet, you can hold down middle button which let's you scroll without dragging the scrollbar. Here the middle mouse brings up the details so I have to click and drag the scrollbar on the right.

Minor thing but will get annoying for people when there are tons of plugins and instances.

**Comment by mottosso** [comment]
> Normally when using tablet, you can hold down middle button which let's you scroll without dragging the scrollbar.

That's a Windows thing. On Unix, middle-click means paste. What's more, isn't it a browser-only thing? I haven't seen this in the Explorer or any other Windows-programs.
