### ISSUE TITLE
Integrate Awesome Font

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-lite#3]
### Goal

At the moment, resources such as background images for buttons and actions, are `.png` images but these should come from https://fortawesome.github.io/Font-Awesome/

### Implementation

As a font, I'd expect an implementation to be simply installing this font and assigning the appropriate unicode letter to each icon. We'll need a mapping from name -> unicode letter as well, for when Pyblish Lite implements "Actions", such that we can assign an icon via it's official name. Like in Pyblish QML.

**Comment by larsbijl** [comment]
worth look at https://github.com/spyder-ide/qtawesome to see if we can refactor from it what we need

**Comment by mottosso** [comment]
There is that, but I'd imagine it being much simpler than needing a third-party library.

Something like this.

- http://stackoverflow.com/a/35171047/478949

In Pyblish QML, I'm doing that, and storing a name -> unicode mapping in a plain json. I'd like that to work here too, less code, less worry and easier to update.

**Comment by mottosso** [comment]
Implemented in 0.3.0
