### ISSUE TITLE
Override Qt bindings

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-lite#30]
### Goal

The available Qt bindings - PySide, PySide2, PyQt4 and PyQt5 - are automatically detected at startup via the `compat.py` module. In case two or more bindings are available and one if preferred, currently there is no way of telling Lite which to pick.

Enable some mechanism with which to specify up-front which bindings to use.

### Motivation

This is primarily intended for use in testing, where tests must be able to specify bindings with which to tests against, but could potentially be useful in an enterprise environment where multiple bindings must be present on the `PYTHONPATH`.

### Implementation

Before searching for available bindings, query the existence of `sys.modules["Qt"]`. This way, a bindings may be manually imported at any point within the process, before launching Lite, and it will not attempt to automatically detect what's available.

**Comment by tokejepsen** [comment]
Thought this was implemented with the Qt vendor; https://github.com/pyblish/pyblish-lite/blob/3538a2fbe9191357ce72da2e5d4ff5dc5441c62a/pyblish_lite/vendor/Qt.py#L104 ?

**Comment by mottosso** [comment]
Yes you are right. This was where Qt.py was born and where the idea of overridable defaults came up first.

Thanks! Closing this!
