### ISSUE TITLE
pip install pyblish-lite

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-lite#41]
### Goal

Enable users to install Pyblish Lite via PyPI.

**Comment by tokejepsen** [comment]
What would be the default Qt binding module? PySide?

**Comment by mottosso** [comment]
Any!

This has actually already been implemented, so closing this.

**Comment by tokejepsen** [comment]
Should there be a default Qt binding module that install as a requirement in the ```setup.py```?

**Comment by mottosso** [comment]
I'm not sure, I think PySide is such a heavy dependency, especially when optional (not needed at all in Maya et. al. for example) that it might not be expected or wanted when wanting to use it in a majority of usecases.

It's in requirements.txt though, that way it's at least a tiny bit more explicit.

```bash
$ pip install -r requirements.txt
```

**Comment by tokejepsen** [comment]
Alright, I guess in the cases where it is needed (pyblish-standalone), good documentation/feedback to the user is enough.

**Comment by mottosso** [comment]
I think so. The trick is also knowing what to do when the user already has PyQt or PySide2 installed. Then we wouldn't want/need to force PySide on them.

A good message with explanation and instructions should suffice. And it's a one-off, so no biggie.
