### ISSUE TITLE
Action Icons

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-lite#53]
**Goal**

To mirror the behavior from ```pyblish-qml```.

**Motivation**

Easier to discover and find plugins that have actions associated with them.

**Implementation**

The behavior should be the exact same as in ```pyblish-qml```; https://github.com/pyblish/pyblish-qml/pull/166

**Comment by tokejepsen** [comment]
It looks like ```pyblish-lite``` doesn't differentiate between processing a plugin and processing an action. This results in the checkbox being colored by the action depending on success/failure.

This means we could leave out the coloring of the action icon, and just display it.

**Comment by tokejepsen** [comment]
Actually this doesn't work out very well. When an plugin is failed and the checkbox is red, running an action that fails as well results in nothing happening in the UI, leaving the user thinking that nothing has happened at all.

**Comment by mottosso** [comment]
Shouldn't be difficult giving actions a unique property for use in the delegate.

It's take another member in the [model](https://github.com/pyblish/pyblish-lite/blob/master/pyblish_lite/model.py), and something to draw that member in the [delegate](https://github.com/pyblish/pyblish-lite/blob/master/pyblish_lite/delegate.py).

[This](https://github.com/pyblish/pyblish-lite/blob/3538a2fbe9191357ce72da2e5d4ff5dc5441c62a/pyblish_lite/control.py#L88) is where an action is triggered, this could also be where this member is updated.

**Comment by tokejepsen** [comment]
> This is where an action is triggered, this could also be where this member is updated.

I don't see any direct interaction between the model and the controller. Should I not update the model in the controller?

**Comment by tokejepsen** [comment]
Actually I think I have something that works, and it emulating the plugin processing.

**Comment by tokejepsen** [comment]
Implemented with https://github.com/pyblish/pyblish-lite/pull/55
