### ISSUE TITLE
Callbacks

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-lite#54]
**Goal**

Support ```pyblish-base``` callback api.

**Implementation**

I theory this should be handled in ```control.py``` but the current logic for toggling is in ```window.py```. Would it be alright to import ```pyblish``` into ```window.py``` or should we find a solution that happens in ```control.py```?

**Comment by mottosso** [comment]
For cleanliness, let's try `control.py`. We can implement an `emit()` there that calls `pyblish.api.emit`.

**Comment by tokejepsen** [comment]
Seems like having an emit function on the controller confuses Qt about emitting. Got an alternative name in mind?

**Comment by tokejepsen** [comment]
I tried using ```index.data(model.Object)``` to fetch the original object, but this returns ```None```. I'm resorting to ```self.data["models"]["instances"].items[index.row()]```

**Comment by tokejepsen** [comment]
Implemented with https://github.com/pyblish/pyblish-lite/pull/56
