### ISSUE TITLE
Small icons and text on OSX

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-lite#62]
## Description

On OSX the icons and text is very small.

![screen shot 2016-09-27 at 11 10 42](https://cloud.githubusercontent.com/assets/1860085/18869215/3d73981a-84a3-11e6-8b00-3f671d3a0cc4.png)

## Expected Results

Would be nice with a text size of a least 10 px or more.

## Minimal steps to reproduce

Using PyQt4, but its the same small size in Nuke and Maya.

**Comment by tokejepsen** [comment]
I'm tempted to fix with by just having a platform query, when setting the point size of the fonts and icons, unless there is a better way?

**Comment by mottosso** [comment]
I think the proper solution is to not specify pixel sizes, but unit sizes.

Qt should have something for this, but I haven't worked with it before. It should be a simple matter of replacing calls to `setSize()` and what not with the equivalent for pixel-less values.

Worst case, yes, we should be able to just double the sizes for OSX, at least for this one scenario you've found.

**Comment by tokejepsen** [comment]
Sorry getting the proper solution with pixel-less values will be too big of a task for me to handle in the time frame I have. Production ready needs this for daily usage. How about a temporary fix, but leave the issue up?

**Comment by mottosso** [comment]
It depends on the fix. If you show me a PR, we could talk about specifics there.

**Comment by BigRoy** [comment]
When using `setPointSize` for fonts they should be similar on all platforms as opposed to `setPixelSize` which might differ. Looking at the code this does seem to done correctly.

Then, with issues still being present these sound related:

http://stackoverflow.com/questions/25761556/qt5-font-rendering-different-on-various-platforms
https://forum.qt.io/topic/40690/solved-size-of-text-is-different-on-windows-os-and-mac-os

Funnily enough these all discuss Qt5 as having a problem with point sizes.

Or could it be the css `font-size` styling that are messing things up?

**Comment by tokejepsen** [comment]
Interesting

> Funnily enough these all discuss Qt5 as having a problem with point sizes.
> Or could it be the css font-size styling that are messing things up?

Seeing this in Nuke, which uses PySide so it shouldn't be anything to do with Qt5, so leaning more towards that it might be an issue with css.

**Comment by tokejepsen** [comment]
css didn't do anything. Its all about the [fonts](https://github.com/pyblish/pyblish-lite/blob/8401f380c0b4d36c8bf66e2511f3f507111abbf7/pyblish_lite/delegate.py)

There is the option of querying the default point size of a font, which is system dependent and add/subtract from that:
```python
from Qt import QtWidgets
point_size = QtWidgets.QFont("Open Sans", 0).pointSize()
print point_size
```

**Comment by tokejepsen** [comment]
Point sizes are all the same :( PR for OSX specific font sizes; https://github.com/pyblish/pyblish-lite/pull/68

**Comment by tokejepsen** [comment]
Initially implemented with https://github.com/pyblish/pyblish-lite/pull/68 but missing the font size on the comment section.

**Comment by mottosso** [comment]
Closing this until it becomes a problem again.
