### ISSUE TITLE
.vendor.Qt - sys.modules[__name__] not working in python 2.7

### ISSUE THREAD

**Issue by kroopson** [pyblish/pyblish-lite#63]
When trying to launch pyblish-lite from python 2.7 I get an ImportError:

```
  File "C:\CODE\pyblish-lite\pyblish_lite\app.py", line 6, in <module>
    from Qt import QtWidgets, QtGui
ImportError: No module named Qt

```
If I change vendor.Qt line 219:
```
-           sys.modules[__name__] = binding()
+           sys.modules["Qt"] = binding()
```

everything works just fine.

I'm running it on Windows 10, cpython 2.7.8 version.

**Comment by mottosso** [comment]
Thanks for reporting this @kroopson! Will have a look in the morning.

**Comment by mottosso** [comment]
Hi @kroopson, I'm having trouble narrowing down the version you are using for this problem.

For one, `vendor.Qt` is [already set to `["Qt"]`](https://github.com/pyblish/pyblish-lite/blob/bfa11df146f9571dcd9b68209e61eed351c410bd/pyblish_lite/vendor/Qt.py#L127), and there is no line 219.

Could it be that you have Qt.py installed elsewhere on your system? That might cause it to first load `vendor.Qt` and *then* load the system-wide one.

Clearly a bug either way, but it would help a lot in fixing it if we could narrow this down.

**Comment by mottosso** [comment]
Let me know if this solves the problem for you!

- https://github.com/pyblish/pyblish-lite/releases/tag/0.4.1
