### ISSUE TITLE
finished signal not emitted on finished

### ISSUE THREAD

**Issue by Eiken** [pyblish/pyblish-lite#67]
finished signal not emitted on finished.

When pyblish prints finished to the console the Qt finished signal in the controller is not emitted

**Comment by mottosso** [comment]
Thanks Erik, I'll have this in by the end of today.

**Comment by mottosso** [comment]
Hi @Eiken, sorry to keep you waiting, looks like I caught a fever. :(

You are welcome to have a look at this, would be fantastic with either a patch or PR.

**Comment by Eiken** [comment]
I checked a little on it.
My first idea was to just emit finished at the end of on_finished() in windows.py but then I saw:
```python
controller.finished.connect(self.on_finished)
```
So that would cause infinite recursion I guess.
Going to see if I can come up with something smarter.

**Comment by Eiken** [comment]
Maybe that connection can be removed cause it don't seem to be used for anything.
on_finished is always called as:
```python
util.defer(500, self.on_finished)
```

**Comment by Eiken** [comment]
```bash
diff --git a/pyblish_lite/window.py b/pyblish_lite/window.py
index 19d8460..a2fbb3a 100644
--- a/pyblish_lite/window.py
+++ b/pyblish_lite/window.py
@@ -488,7 +488,6 @@ class Window(QtWidgets.QDialog):
         controller.was_validated.connect(self.on_was_validated)
         controller.was_published.connect(self.on_was_published)
         controller.was_acted.connect(self.on_was_acted)
-        controller.finished.connect(self.on_finished)
 
         # Discovery happens synchronously during reset, that's
         # why it's important that this connection is triggered
@@ -857,6 +856,7 @@ class Window(QtWidgets.QDialog):
             self.info("Stopped due to error(s), see Terminal.")
         else:
             self.info("Finished successfully!")
+            self.controller.finished.emit()
 
     # -------------------------------------------------------------------------
     #
```

This works as expected but maybe it breaks something somwhere I don't know about.

**Comment by mottosso** [comment]
Thanks, however this creates a cyclic dependency between the controller and window.

The window is meant to listen for signals coming from the controller, whereas in this case the window tells the controller to emit a signal that the window is then listening for.

You removed the listening bit, which leaves us in a situation where *most* signals are coming from controller to window, and where *one* signal does the opposite. Not ideal.
