### ISSUE TITLE
Action icon missing on "all"

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-lite#84]
**Description**

If an action has the ```on``` setting to "all", the action icon doesn't show all the time like it would be expected to.

**Comment by mottosso** [comment]
What version is this?

There was a change recently, the bug might have slipped in around that point.

- https://github.com/pyblish/pyblish-lite/commit/3c86cd6a06bda151853834ecd642d31abb6863cf

If not, it possible it fixes it.

**Comment by tokejepsen** [comment]
I'm on the latest commit https://github.com/pyblish/pyblish-lite/commit/6e7286910e328e41ea4a02a4d3e61cad7eb9f8e5

**Comment by mottosso** [comment]
Ah, that might explain it. Try reverting and see if that commit introduced this bug.

**Comment by hannesdelbeke** [comment]
can this issue be closed? PR went in
