### ISSUE TITLE
Actions trying to run on previous plugin

### ISSUE THREAD

**Issue by mkolar** [pyblish/pyblish-lite#87]
Hey guys.

After updating to latest release of pyblish-lite, our actions stopped working across the board. It happens from this commit onwards 88148c3c3ca03e9c3c6f80e7f526198f79a9c292 . When I revert to a commit before that everything works.

Any action that I run seems to be attempting to run on a plugin on position above. 

The screencast doesn't show the action menu, but I right clicked on `output location existence` and selected an action. After that you can see that it tries to run it on the plugin above `Validate Publish path`.

Here's the log that comes up.

```
Stopped due to error(s), see Terminal.
Stopped due to error(s), see Terminal.
plugin is: <class 'validate_publish_path.ValidatePublishPath'>
Preparing <class 'validate_deadline_output_existence.RepairOutputLocation'>..
Action prepared.
Traceback (most recent call last):
  File "K:\.core\dev\pyblish\pyblish-lite\pyblish_lite\control.py", line 92, in on_next
    result = pyblish.plugin.process(plugin, context, None, action.id)
  File "K:\.core\dev\pyblish\pyblish-base\pyblish\plugin.py", line 443, in process
    result = __explicit_process(plugin, context, instance, action)
  File "K:\.core\dev\pyblish\pyblish-base\pyblish\plugin.py", line 481, in __explicit_process
    % (plugin, action))
AssertionError: <class 'validate_publish_path.ValidatePublishPath'> did not have action: 910884f4-c345-4ef6-8e85-4a026129141e. This is a bug
Stopping..
```

![insta](https://cloud.githubusercontent.com/assets/3333008/21896251/0158b094-d8e6-11e6-9e97-3a75500db35e.gif)

**Comment by mottosso** [comment]
Thanks @mkolar!

**Comment by mottosso** [comment]
It's from a recent release.

- https://github.com/pyblish/pyblish-lite/pull/85

@p4vv37 Can you spot what's going on?

**Comment by p4vv37** [comment]
Ok, moment...

**Comment by p4vv37** [comment]
I guess, that the problem appeared because of the change of indexing of the treeView in QT5, but I've got to check it, I'll try to do it later today.
You're working on Maya 2017?

**Comment by p4vv37** [comment]
Ok, I've got it: I did not include the mapping from filter's index to source model's index. I'm committing necessary changes.

@mkolar - sorry for that, I hope It did not cause you that much of a problem

**Comment by mkolar** [comment]
@p4vv37 no worries. I'm not suicidal enough to put new update to production before I try them out
