### ISSUE TITLE
Scaling Desktop in Windows

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-lite#93]
**Description**

When scaling the desktop in Windows, the UI elements gets overlaid.

![image](https://cloud.githubusercontent.com/assets/1860085/26240645/fd0e2e38-3c81-11e7-91db-d585fcfa065c.png)

Practically this happens on a 4K monitor when scaling the desktop.

**Expected Results**

Same interface on any scaled desktop.

**Minimal steps to reproduce**

In windows 10 scale the desktop by right-click on desktop > Display Settings > Change the size of text, apps and other items > change to 150 %.

**Comment by mottosso** [comment]
Thanks @tokejepsen, by eye it looks like we need to include a scale factor in [delegate.py](https://github.com/pyblish/pyblish-lite/blob/master/pyblish_lite/delegate.py).
